app/urls.py
from django.urls import path
from app import views
app_name='app'
urlpatterns = [
    path('',views.index,name="index"),
    path('categories/', views.category, name='category'),
    path('product/', views.featureproduct, name='allproduct'),
    path('categories/<int:category_id>/', views.product_list, name='product'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('wishlist/', views.view_wishlist, name='wishlist'),
    path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('product/<int:product_id>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
   
    path('cart/', views.cart, name='cart'),
    path('cart/<int:cart_item_id>/remove_cart/', views.remove_cart, name='remove_cart'),
    path('checkout/', views.checkout, name='checkout'),

    
    path('success/', views.success, name='success'),
    
    path('cancel/', views.cancel, name='cancel'),
]

ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views
from django.conf import settings  
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

app/templates/app/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
   {% load static %}
   <link rel="stylesheet" href="{% static 'css/style.css'%}">
 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
     <!-- Include Razorpay Checkout script -->
     <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
</head>
  <body>
    <div class="main-navbar shadow-sm sticky-top">
        <div class="top-navbar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 my-auto d-none d-sm-none d-md-block d-lg-block">
                        <h5 class="brand-name">Dream Heaven</h5>
                    </div>
                    
                    <div class="col-md-7 my-auto">
                        <ul class="nav justify-content-end">
                            
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'app:cart' %}">
                                    <i class="fa fa-shopping-cart"></i> 
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'app:wishlist' %}" >
                                    <i class="fa fa-heart"></i>  {{ wishlist_count }}
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-user"></i> 
                                    {% if user.is_authenticated %}
                                        {{ user.username }}
                                    {% else %}
                                        Guest
                                    {% endif %}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    {% if user.is_authenticated %}
                                        <li><a class="dropdown-item" href="{% url 'app:profile' %}">Profile</a></li>
                                        <li><a class="dropdown-item" href="{% url 'app:logout' %}">Logout</a></li>
                                    {% else %}
                                        <li><a class="dropdown-item" href="{% url 'app:login' %}">Login</a></li>
                                        <li><a class="dropdown-item" href="{% url 'app:signup' %}">Signup</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a class="navbar-brand d-block d-sm-block d-md-none d-lg-none" href="#">
                    Dream Heaven
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app:category' %}">All Categories</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app:allproduct' %}">Featured Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Electronics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Men</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">kids</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">women</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Accessories</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link" href="#">Appliances</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container p-3 my-3">
        <div class="row">
          <div class="col-md-12">
            <!--Any flash messages pop up in any page because this is the base template-->
            {% if messages %}
            <div class="alert alert-dismissible" role="alert">
              {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
              {% endfor %}
              <button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endif %} 
    {% block body %}
    {% endblock %}
    <script src="https://kit.fontawesome.com/7998acc56d.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/app/cancel.html
{% comment %} templates/app/cancel.html {% endcomment %}

{% extends "base.html" %} 
{% block title %} Cancel {% endblock title%} 
{% block content %}
<div class="alert alert-info" role="alert">
  Forgot to add something to your cart?
  <a
      href="{% url 'products:product-list' %}"
      >Go to Products</a
    >
</div>
{% endblock content %}

app/templates/app/cart.html
{% extends 'app/base.html' %}
{% block body %}




 <section class="bg-light py-4 my-5" >
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h4 class="mb-3">Cart Items</h4>
                <hr style="border-color:#b8bfc2;">
            </div>
        </div>
        
       
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product Name</th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th> Amount</th>
                    <th>Remove</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                <tr>
                    <td><img src="{{ item.product.photo.url }}" height="75px" alt="{{ item.product.name }}"></td>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.product.price }}</td>
                    <td>
                        
                               
                                
                                <input type="number" name="quantity" class="form-control input-number" value="{{ item.quantity }}" min="1" max="{{ item.product.quantity }}" width="10">
                               
                               
                    </td>
                   
                   <td>{{ item.subtotal }}</td>
                   <td> <a  href="{% url 'app:remove_cart' item.id %}"  class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Remove</a></td>
                </tr>
                {% endfor %}
                <tr>
                    <td></td>
                    <td></td>
                    <td colspan="2"><b>Total Amount</b></td>
                    <td>{{ total_amount }}</td>
                 
                    <td><a href="{% url 'app:checkout' %}" class="btn btn-primary btn-sm"><i class="fa fa-check-circle"></i> Check Out</a></td>
                </tr>
            </tbody>
        </table>
       
        <a href="">Continue Shopping</a>
    </div>
</section> 



{% endblock %} 

app/templates/app/catagories.html
{% extends 'app/base.html' %}
{% block body %}
   
           

<section class=" bg-light d-flex  justify-content-center align-item-center h-100 min-vh-100">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="mb-4 p-3 text cat ">Our Categories</h2>
        </div>
    <div class="row gy-2">
        {% for category in categories %}
        <div class="col-lg-3   col-md-4 ">
           
            <a  href="{% url 'app:product' category.id %}" style="text-decoration: none;">
            <div class=" card box h-100 d-flex p-1 flex-colum text-dark ">
                <div class="card-body">
                <img src="{{ category.photo.url }}" class="img-fluid card-img-top rounded" alt="{{ category.name }}">
                <h3 class="card-title">{{ category.name }}</h3>
             </div>
            </div>
</a>
        </div>
        {% endfor %}
    </div>
</div>
</section>













 

    
         
 
    
           
{% endblock %}

app/templates/app/checkout.html
{% extends 'app/base.html' %}
{% block body %}

<div class="py-3 py-md-4 checkout">
    <div class="container">
        <h4>Checkout</h4>
        <hr>

        <div class="row">
            <div class="col-md-12 mb-4">
                <div class="shadow bg-white p-3" >
                    <h4 class="text-primary">
                        Item Total Amount :
                        <span class="float-end"><i class="fa fa-inr" aria-hidden="true"></i>{{ total_amount }}</span> <!-- Adjust this to show the total amount -->
                    </h4>
                    <hr>
                    <small>* Items will be delivered in 3 - 5 days.</small>
                    <br/>
                    <small>* Tax and other charges are included ?</small>
                   

                </div>     
            </div>
            <div class="col-md-12 align-self-center">
                <div class="shadow bg-white p-3">
                    <h4 class="text-primary">
                        Basic Information
                    </h4>
                    <hr>

                    <form action="{% url 'app:checkout' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="name" class="form-label">Full Name</label>
                            <input type="text" name="name" class="form-control"  placeholder="Enter Full Name" required>
                        </div>
                        <div class="mb-3 col-md-6">
                            <label for="email" class="form-label">Email Address</label>
                            <input type="email" name="email" class="form-control" placeholder="Enter Email Address" required>
                        
                        </div>
                        </div>

                        <div class="mb-3">
                            <label for="address1" class="form-label">Address Line 1</label>
                            <input type="text" name="address1" class="form-control" placeholder="Enter Address Line 1" required>
                        </div>
                        <div class="mb-3">
                            <label for="address2" class="form-label">Address Line 2</label>
                            <input type="text" name="address2" class="form-control" placeholder="Enter Address Line 2">
                        </div>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="city" class="form-label">City</label>
                                <input type="text" name="city" class="form-control" placeholder="Enter City" required>
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="state" class="form-label">State</label>
                                <input type="text" name="state" class="form-control" placeholder="Enter State" required>
                            </div>
                            <div class="col-md-2 mb-3">
                                <label for="zip_code" class="form-label">Zip Code</label>
                                <input type="text" name="zip_code" class="form-control" placeholder="Enter Zip Code" required>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="phone" class="form-label">Phone Number</label>
                            <input type="text" name="phone" class="form-control" placeholder="Enter Phone Number" required>
                        </div>
                        <div class="mb-3">
                            <label>Select Payment Mode:</label><br>
                          
                          
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_method" id="cod" value="COD">
                                <label class="form-check-label" for="cod">Cash on Delivery</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_method" id="card" value="card">
                                <label class="form-check-label" for="card">Credit/Debit Card</label>
                            </div>
                        </div>
                        <button type="submit" id="payment-btn" class="btn btn-primary">Place Order</button>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>
<script>
    function togglePaymentButton() {
        var paymentMethod = document.querySelector('input[name="payment_method"]:checked').value;
        var paymentButton = document.getElementById('payment-btn');

        if (paymentMethod === 'card') {
            paymentButton.textContent = 'Pay with Razorpay';
            paymentButton.onclick = function () {
                var options = {
                    key: "NuSQgBnmlJJ25h",
                    amount: "{{ razorpay_amount }}",
                    currency: "INR",
                    name: "Your Store",
                    description: "Order Payment",
                    image: "",
                    order_id: "{{ razorpay_order_id }}",
                    handler: function (response) {
                        console.log("Payment successful:", response);
                        document.forms[0].submit(); // Submit the form after successful payment
                    },
                    prefill: {
                        name: "",
                        email: "",
                        contact: ""
                    },
                    theme: {
                        color: "#3399cc"
                    }
                };
                var rzp = new Razorpay(options);
                rzp.open();
            };
        } else {
            paymentButton.textContent = 'Place Order';
            paymentButton.onclick = function () {
                document.forms[0].submit(); // Submit the form for COD
            };
        }
    }

    // Call the togglePaymentButton function on page load
    window.onload = togglePaymentButton;
</script>

{% endblock %}

app/templates/app/featureproduct.html
{% extends 'app/base.html' %}
{% block body %}
{% load static %}

<section class=" bg-light d-flex  justify-content-center align-item-center h-100 min-vh-100">
  
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="mb-4 p-2 text-dark cat">Our Products</h4>
            </div>
            <div class="row">
            {% for product in products %}
            <div class="col-md-3">
                <div class="product-card">
                    <a href="{% url 'app:product_detail' product.id %}">
                    <div class="product-card-img">
                        <label class="stock bg-success">In Stock</label>
                        <img src="{{ product.photo.url }}" alt="Laptop">
                    </div>
                    <div class="product-card-body">
                        <p class="product-brand"> {{ product.brand}} </p>
                        <h5 class="product-name">
                           <a href="">
                            {{ product.name}} 
                           </a>
                        </h5>
                        <p class="card-text">{{ product.smalldescription }}</p>
                        <div>
                            <span class="card-text text"><i class="fa fa-inr" aria-hidden="true"></i>{{ product.price }}</span>
                         
                        </div>
                    </a>
                        <div class="mt-2">
                            <a href="" class="btn btn1">Add To Cart</a>
                            <a href="" class="btn btn1"> <i class="fa fa-heart"></i> </a>
                            <a href="{% url 'app:product_detail' product.id %}" class="btn btn1"> View </a>
                        </div>
                    </div>
                </div>
            </div>
                  
      {% endfor %}
    </div>
            
           
        </div>
    </div>
</div>

</section>
           
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% block body %}
{% load static %}
<div class="container jb my-5">
  <div class="jumbotron jumbotron-bg">
    <h1 class="display-4">Welcome to our Ecommerce Site!</h1>
    <p class="lead">Browse through our wide range of products and find what you need.</p>
    <hr class="my-4">
    <p>Start shopping now!</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Shop Now</a>
  </div>
</div>

 


{% endblock %}

app/templates/app/product.html
{% extends 'app/base.html' %}
{% block body %}
{% load static %}


<section class=" bg-light d-flex  justify-content-center align-item-center h-100 min-vh-100">
   
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="mb-4 p-2 text-dark cat">{{ category.name }}</h4>
            </div>
            <div class="row">
              
            {% for product in products %}
            <div class="col-md-3">
               
                <div class="product-card">
                    <a href="{% url 'app:product_detail' product.id %}">
                    <div class="product-card-img">
                        <label class="stock bg-success">In Stock</label>
                        <img src="{{ product.photo.url }}" alt="Laptop">
                    </div>
                    <div class="product-card-body">
                        <p class="product-brand"> {{ product.brand}} </p>
                        <h5 class="product-name">
                           <a href="">
                            {{ product.name}} 
                           </a>
                        </h5>
                        <p class="card-text">{{ product.smalldescription }}</p>
                        <div>
                            <span class="card-text text-dark "><i class="fa fa-inr" aria-hidden="true"></i>{{ product.price }}</span>
                         
                        </div>
                    </a>
                        <div class="mt-2">
                            <a href="" class="btn btn1">Add To Cart</a>
                           
                            <a href="{% url 'app:product_detail' product.id %}" class="btn btn1"> View </a>
                        </div>
                    </div>
                </div>
            </div>
                  
      {% endfor %}
    </div>
            
           
        </div>
    </div>
</div>

</section>

  
{% endblock %}

app/templates/app/product_detail.html
{% extends 'app/base.html' %}
{% block body %}
{% load static %}





<section class=" bg-dark d-flex  justify-content-center  p-5   align-item-center h-100 min-vh-100">

    <div class="container">
        <div class="row">
            <div class="col-md-5 mt-3">
                <div class="bg-white border">
                    <img src="{{ product.photo.url }}" class="w-100" alt="{{ product.name }}" style="height:450px">
                </div>
            </div>
            <div class="col-md-7 mt-3">
                <div class="product-view text-white ">
                    <h4 class="product-name ">
                        {{ product.name }}
                        <label class="label-stock bg-success">In Stock</label>
                    </h4>
                    <hr>
                    <p class="product-path text-white">
                        Home / Category / Product /{{product.id}}
                    </p>

                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                    </div>
                    {% endfor %}
                    <p class="product-brand"> {{ product.brand}} </p>
                    <div>
                        <p class="card-text text-white"><i class="fa fa-inr" aria-hidden="true"></i> {{ product.price }}
                        </p>
                    </div>
                    {% if product.size %}
                    <p>Size: {{ product.size.all }}</p>
                    {% endif %}
                    <div class="mt-2">
                        <div class="input-group">
                            <span class="btn btn1" onclick="decrementQuantity()"><i class="fa fa-minus" style="color:white"></i></span>
                            <input type="text" class="input-quantity" id="quantity" name="quantity" value="1">
                            <span class="btn btn1" onclick="incrementQuantity()"><i class="fa fa-plus" style="color:white"></i></span>
                        </div>
                    </div>
                    <div class="mt-2">
                        
                       
                            <a href="{% url 'app:add_to_cart' product.id %}" type="submit" class="btn btn1 bg-primary"> <i class="fa fa-shopping-cart"></i> Add To Cart</a>
                        {% if product_in_wishlist %}
                        <a href="{% url 'app:add_to_wishlist' product_id=product.id %}" class="btn btn1 bg-primary"> <i class="fa fa-heart"></i>  <i class="fa fa-heart"></i>Remove
                            from Wishlist</a>
                        {% else %}
                        <a href="{% url 'app:add_to_wishlist' product_id=product.id %}" class="btn btn1 bg-primary"> <i class="fa fa-heart"></i> Add to
                            Wishlist</a>
                        {% endif %}

                    </div>
                    <div class="mt-3">
                        <h5 class="mb-0">Small Description</h5>
                        <p>
                            {{ product.smalldescription }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 mt-3">
                <div class="card">
                    <div class="card-header bg-white">
                        <h4>Description</h4>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ product.description }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

</section>




<section class=" bg-light d-flex  justify-content-center align-item-center h-100 min-vh-100">
   
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="mb-4 p-2 text cat">Similar Products</h4>
            </div>
            <div class="row">
              
                {% for similar_product in similar_products %}
            <div class="col-md-3">
               
                <div class="product-card">
                    <a href="{% url 'app:product_detail' similar_product.id %}">
                    <div class="product-card-img">
                        <label class="stock bg-success">In Stock</label>
                        <img src="{{ similar_product.photo.url }}" alt="{{ similar_product.name }}" style="max-width: 100%;">
                    </div>
                    <div class="product-card-body">
                        <p class="product-brand"> {{ similar_product.brand }} </p>
                        <h5 class="product-name">
                           <a href="">
                            {{ similar_product.name }}
                           </a>
                        </h5>
                        <p class="card-text">{{ similar_product.smalldescription}}</p>
                        <div>
                            <span class="card-text text-dark "><i class="fa fa-inr" aria-hidden="true"></i>{{ similar_product.price }}</span>
                         
                        </div>
                    </a>
                        <div class="mt-2">
                            <a href="" class="btn btn1">Add To Cart</a>
                           
                            <a href="{% url 'app:product_detail' product.id %}" class="btn btn1"> View </a>
                        </div>
                    </div>
                </div>
            </div>
                  
      {% endfor %}
    </div>
            
           
        </div>
    </div>
</div>

</section>











<script>
function incrementQuantity() {
    var quantityInput = document.getElementById('quantity');
    var currentValue = parseInt(quantityInput.value);
    quantityInput.value = currentValue + 1;
}

function decrementQuantity() {
    var quantityInput = document.getElementById('quantity');
    var currentValue = parseInt(quantityInput.value);
    if (currentValue > 1) {
        quantityInput.value = currentValue - 1;
    }
}





</script>









{% endblock %}

app/templates/app/success.html
{% comment %} templates/app/success.html {% endcomment %}

{% extends "base.html" %} 
{% block title %} Success {% endblock title%} 
{% block content %}
<div class="alert alert-success" role="alert">
  Thanks for purchasing our product
  <a
      href="{% url 'products:product-list' %}"
      >Go to Products</a
    >
</div>
{% endblock content %}

app/templates/app/wishlist.html
{% extends 'app/base.html' %}
{% block body %}
{% load static %}

<section class=" bg-light d-flex  justify-content-center align-item-center h-100 min-vh-100">
<div class="container ">
    <h2 class="text-dark ">My Wishlist</h2>
    <div class="row">
        {% for item in wishlist_items %}
        <div class="col-lg-3 col-md-4 col-sm-12  m-4" style="width:300px">
            <div class="card box h-100 d-flex p-2 flex-colum ">
                
                <img src="{{ item.product.photo.url }}" class="card-img-top " alt="{{ item.product.name }}" style="max-height: 300px; max-width:300px ">
              
                <div class="card-body product-card-body">
                    <p class="product-brand"> {{ item.product.brand}} </p>
                    <h5 class="card-title product-name">{{ item.product.name }}</h5>
                    <p class="card-text">{{ item.product.smalldescription }}</p>
                    <div>
                        <span class="card-text text-dark"><i class="fa fa-inr" aria-hidden="true"></i>{{ item.product.price }}</span>
                     
                    </div>
                    <!-- Add more product details as needed -->
                    <a href="{% url 'app:product_detail' item.product.id %}" class="btn m-3 btn-primary">View Product</a>
                    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div> 
</section>
{% endblock %}